version: "3"

services:
  node:
    build:
      context: ./docker/node
    environment:
      PORT: "${NODE_PORT:-8080}"
      DEBUG: "express:*,socket.io:*,myapp:*"
      DEBUG_DEPTH: "4"
      DEBUG_COLORS: "true"
      DEBUG_HIDE_DATE: "true"
    ports:
      - "${NODE_PORT:-8080}:8080"
    volumes:
      - "./workspace:/app"
    tty: true
    depends_on: 
      - mongo

  mongo:
    build:
      context: ./docker/mongo
    restart: always
    tty: true
    ports:
      - 27017:27017
  
  python:
    build: ./docker/python
    restart: always
    tty: true
    environment:
      DISPLAY: 10.0.75.1:0.0
    volumes:
      - "./python:/app"
    depends_on: 
      - mongo